import { Patient, Doctor, HealthRecord } from './types';

export const PATIENTS: Patient[] = [
  {
    id: '1',
    name: 'Eleanor Vance',
    age: 72,
    gender: 'Female',
    avatar: 'https://picsum.photos/seed/eleanor/200',
    appointmentTime: '09:15 AM',
    room: 'Room 4B',
    reason: 'Post-op Follow-up (Cardiac)',
    status: 'Arrived',
  },
  {
    id: '2',
    name: 'Julian Rossi',
    age: 29,
    gender: 'Male',
    avatar: 'https://picsum.photos/seed/julian/200',
    appointmentTime: '10:30 AM',
    room: 'Room 1A',
    reason: 'Routine Physical Examination',
    status: 'In-Progress',
  },
  {
    id: '3',
    name: 'Sarah Jenkins',
    age: 45,
    gender: 'Female',
    avatar: 'https://picsum.photos/seed/sarah/200',
    appointmentTime: '08:00 AM',
    room: 'Completed',
    reason: 'Allergy Consultation',
    status: 'Completed',
  },
  {
    id: '4',
    name: 'Mark Thompson',
    age: 34,
    gender: 'Male',
    avatar: 'https://picsum.photos/seed/mark/200',
    appointmentTime: '11:45 AM',
    room: 'Upcoming',
    reason: 'Suture Removal',
    status: 'Upcoming',
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Elena Rodriguez',
    specialty: 'Neurology',
    experience: 12,
    rating: 4.9,
    avatar: 'https://picsum.photos/seed/elena/200',
    availability: 'Next Avail: 2h',
    languages: ['English', 'Spanish'],
    tags: ['Recommended'],
  },
  {
    id: '2',
    name: 'Dr. Julian Vance',
    specialty: 'Internal Medicine',
    experience: 8,
    rating: 4.7,
    avatar: 'https://picsum.photos/seed/vance/200',
    availability: 'Next Avail: Tomorrow',
    languages: ['English', 'Telehealth only'],
    tags: ['Near You'],
  },
];

export const RECORDS: HealthRecord[] = [
  {
    id: '1',
    patientId: 'demo-user',
    title: 'Comprehensive Blood Panel',
    category: 'Lab',
    date: '2024-03-15T09:00:00Z',
    clinic: 'Metabolic Health Center',
    result: '92',
    unit: 'mg/dL',
    status: 'Normal',
    createdAt: '2024-03-15T09:00:00Z',
  },
  {
    id: '2',
    patientId: 'demo-user',
    title: 'Cardiovascular Assessment',
    category: 'Lab',
    date: '2024-03-08T10:00:00Z',
    clinic: 'Heart & Vascular Institute',
    result: '38',
    unit: 'mg/dL',
    status: 'Abnormal',
    createdAt: '2024-03-08T10:00:00Z',
  },
  {
    id: '3',
    patientId: 'demo-user',
    title: 'Urinalysis Screen',
    category: 'Lab',
    date: '2024-02-22T11:00:00Z',
    clinic: 'General Wellness Clinic',
    result: 'Negative',
    status: 'Normal',
    createdAt: '2024-02-22T11:00:00Z',
  },
];
